### ISSUE TITLE
"Fatal error: write after end" - 1.4.2

### ISSUE THREAD

**Issue by tkambler** [substack/bulkify#18]
```
Running "browserify:build" (browserify) task
Fatal error: write after end
Error: write after end
    at writeAfterEnd (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:161:12)
    at DuplexWrapper.Writable.write (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:208:5)
    at Transform._transform (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/index.js:21:12)
    at Transform._read (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at clearBuffer (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/node_modules/readable-stream/lib/_stream_writable.js:316:5)
    at onwrite (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/node_modules/readable-stream/lib/_stream_writable.js:274:7)
    at WritableState.onwrite (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/node_modules/readable-stream/lib/_stream_writable.js:106:5)
    at afterTransform (/home/ubuntu/projects/xxx/gui-assessment-renderer/node_modules/bulkify/node_modules/readable-stream/lib/_stream_transform.js:104:5)
```

**Comment by tkambler** [comment]
Had to downgrade to 1.2.0.

**Comment by netinhoteixeira** [comment]
Talking with colleagues we saw that problem exists in  1.4.2 version and it say that it happens because it try to write after end.
Looking for the exactly line and problem on code we saw this:
https://github.com/substack/bulkify/compare/799f4420c1aa9173ed395a2425f7974077e06333...master#diff-168726dbe96b3ce427e7fedce31bb0bcR22

You need to comment the ```sm.end()``` to work again. So, we don't know if it is right to comment that line. But it work again.

CYA,

**Comment by euprogramador** [comment]
I am having the same problem in using browserify.

generating the error Error: write after the end

This is generated because of the closure of the flow.

```javascript 
return through(function (buf, enc, next) {
        sm.write(buf)
        sm.end()   <--- on here
        sm.pipe(concat(function (output) {
            next(null, output)
        }))
    })`

please some correction hint?

i fixed my version 1.1.1.
